//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ilerlemeTakipUygulaması
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ilerlemeTakipEntities : DbContext
    {
        public ilerlemeTakipEntities()
            : base("name=ilerlemeTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kayit> kayit { get; set; }
        public virtual DbSet<Ağustos> Ağustos { get; set; }
        public virtual DbSet<ARALIK> ARALIK { get; set; }
        public virtual DbSet<EKİM> EKİM { get; set; }
        public virtual DbSet<EYLÜL> EYLÜL { get; set; }
        public virtual DbSet<Haziran> Haziran { get; set; }
        public virtual DbSet<KASIM> KASIM { get; set; }
        public virtual DbSet<Mart> Mart { get; set; }
        public virtual DbSet<Mayıs> Mayıs { get; set; }
        public virtual DbSet<Nisan> Nisan { get; set; }
        public virtual DbSet<Ocak> Ocak { get; set; }
        public virtual DbSet<Şubat> Şubat { get; set; }
        public virtual DbSet<tblilerleme> tblilerleme { get; set; }
        public virtual DbSet<tblkayıtlar> tblkayıtlar { get; set; }
    }
}
